name: exam8
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  go_router: ^14.2.8
  dio: ^5.7.0
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  assets:
    - assets/images/
    - assets/icons/

  uses-material-design: true

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen/Sen-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sen/Sen-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sen/Sen-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sen/Sen-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sen/Sen-ExtraBold.ttf
          weight: 800

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/src/common/l10n
  output_dir: lib/src/common/l10n/generated